# Generated by Django 3.0.3 on 2020-03-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('SemesterID', 'ProgramID', 'BatchID', 'CourseID', 'Section')},
        ),
    ]
