# Generated by Django 3.0.3 on 2020-03-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0002_auto_20200328_1149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistered',
            unique_together={('SemesterID', 'ProgramID', 'BatchID', 'CourseID', 'Section', 'StudentID')},
        ),
        migrations.RemoveField(
            model_name='courseregistered',
            name='EmployeeID',
        ),
    ]
