# Generated by Django 3.0.3 on 2020-04-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0003_auto_20200328_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1, null=True)),
                ('LectureNo', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('Duration', models.FloatField()),
                ('Presence', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('BatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Batch')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Course')),
                ('ProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Program')),
                ('SemesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1, null=True)),
                ('EvaluationNumber', models.PositiveIntegerField()),
                ('Weightage', models.FloatField()),
                ('TotalMarks', models.FloatField()),
                ('ObtainedMarks', models.FloatField()),
                ('Type', models.CharField(choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz'), ('Mid Exam', 'Mid Exam'), ('Lab Task', 'Lab Task'), ('Final Exam', 'Final Exam')], max_length=20)),
                ('BatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Batch')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Course')),
                ('ProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Program')),
                ('SemesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Semester')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='PermanentAddress',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='City',
            new_name='PermanentCity',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='PostalCode',
            new_name='PermanentPostalCode',
        ),
        migrations.AddField(
            model_name='employee',
            name='PermanentAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='PermanentCity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='PermanentPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='PermanentPostalCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='TemporaryAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='TemporaryCity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='TemporaryPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='TemporaryPostalCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PermanentPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TemporaryAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TemporaryCity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TemporaryPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TemporaryPostalCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='CourseType',
            field=models.CharField(choices=[('Elective', 'Core'), ('Elective', 'Elective')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programoutline',
            name='CourseType',
            field=models.CharField(choices=[('Elective', 'Core'), ('Elective', 'Elective')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Status',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Graduated', 'Graduated')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CLO',
        ),
        migrations.AddField(
            model_name='evaluations',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluations',
            unique_together={('SemesterID', 'ProgramID', 'BatchID', 'CourseID', 'Section', 'StudentID', 'EvaluationNumber')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('SemesterID', 'ProgramID', 'BatchID', 'CourseID', 'Section', 'StudentID', 'LectureNo')},
        ),
    ]
