# Generated by Django 3.0.3 on 2020-04-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0004_auto_20200420_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evaluations',
            new_name='Evaluation',
        ),
        migrations.AddField(
            model_name='employee',
            name='CNIC',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='DOB',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
