# Generated by Django 3.0.3 on 2020-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0005_auto_20200420_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
